url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Flávio Pereira"

excerpt_separator: <!--more-->

collections:
  - python
  - ruby
  - pawn
  - c++
  - c#
  - php
  - html
  - css
  - javascript
  - react
  - nodejs